config/routes.rb
ShopApp::Application.routes.draw do
  
  # Admin section
  namespace :admin do
    devise_for :admin_users
    root :to => "orders#index"
    match "orders/show" => "orders#show"
    resources :shop, :categories, :products, :orders
  end

  
  root :to => "shop#index" 
  get "shop/index"
  
  resources :categories, :products, :orders
  # Products Controller Routes
  #match 'products/' => "products#index"
  #match 'product/:id' => "products#show"
  # Categories Controller Routes
  #match "categories/" => "categories#index"
  #match "categories/:id" => "categories#show"
  # Orders Controller Routes
  match "orders/add/:product_id" => "orders#add_product"
  match "orders/show" => "orders#show"
  match "orders/remove/:order_item_id" => "orders#remove_item"
  match "orders/confirm/:id" => "orders#confirm"
  match "products_search" => "products#search"
  match "hello" => 'hello#greeting'
  match "spa" => 'spa#index'
  
  match "spaLast" => 'spa#getLastOrder'
  match "spaCheckout" => 'spa#confirmOrder'
  match "spaProducts" => 'spa#getProducts'
  match "spaCategories" => 'spa#getCategories'
  
  match "fakeLogin" => 'fakelogin#login'
  match "fakelogout" => 'fakelogin#logout'
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  attr_accessible :first_name, :last_name
  has_many :orders
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :products
  
  def to_s
    return name
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :buyer_id, :confirmed
  has_many :order_items
  belongs_to :buyer
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  attr_accessible :order_id, :price, :product_id, :quantity
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :description, :price, :category_id
  belongs_to :category
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_filter :authenticate_admin_admin_user!
  
  
  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find_by_id(params[:id])
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.create(params[:category])
    redirect_to(:controller => "admin/categories", :action => "index")
  end
  
  def update
    @category = Category.find_by_id(params[:id])
    @category.name = params[:category][:name]
    @category.save
    redirect_to(:controller => "admin/categories", :action => "index")
  end
  
  def destroy
    @category = Category.find_by_id(params[:id])
    @category.products.each do |product|
      product.destroy
    end
    @category.destroy
    redirect_to(:controller => "admin/categories", :action => "index")
  end
  
end 

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController
  
  def index
    @orders = Order.all
  end
  
  def show
    @order = Order.find_by_id(params[:id])
    @order_items = OrderItem.where(:order_id => params[:id])
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  
  def index
    @products = Product.all
  end
  
  def show
    @product = Product.find_by_id(params[:id])
    @categories = Category.all
  end
  
  def new
    @product = Product.new
    @categories = Category.all
  end
  
  def create
    @product = Product.create(params[:product])
    redirect_to admin_products_path
  end
  
  def update
    @product = Product.find_by_id(params[:id])
    @product.name = params[:product][:name]
    @product.price = params[:product][:name]
    @product.category = params[:product][:category]
    @product.save
    redirect_to admin_products_path
  end
  
  def destroy
    @product = Product.find_by_id(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end
  
end 

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_cart, :current_fakeuser
  
  def current_fakeuser
    cookies[:fakelogin]
  end
  
  def current_buyer
    @current_buyer_id = cookies[:buyer_id]
    @current_buyer = Buyer.find_by_id(@current_buyer_id)
    if @current_buyer == nil
      @current_buyer = Buyer.create
      Order.create(buyer_id: @current_buyer.id, confirmed: false)
      cookies[:buyer_id] = { :value => @current_buyer.id, :expires => 1.week.from_now }
    end
    return @current_buyer
  end
  
  def current_cart
    @current_cart = OrderItem.where(:order_id => current_buyer().orders.where(:confirmed => false).last.id).all
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find_by_id(params[:id])
    @products = @category.products
  end
end

app/controllers/fakelogin_controller.rb
class FakeloginController < ApplicationController
  
  def login
    cookies[:fakelogin] = 'FakeUser'
    redirect_to :controller => 'shop', :action => 'index'
  end
  
  def logout
    cookies[:fakelogin] = nil
    redirect_to :controller => 'shop', :action => 'index'
  end
  
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def greeting    
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def show
    @cart = current_buyer().orders.where(:confirmed => false).last
  end
  
  def add_product
    @product = Product.find_by_id(params[:product_id])
    @order = current_buyer().orders.last
    @existing = OrderItem.where(:order_id => @order.id, :product_id => @product.id).first
    if @existing == nil
      @order_item = OrderItem.create(order_id: @order.id, product_id: @product.id, price: @product.price, quantity: 1)
    else
      @existing.quantity += 1
      @existing.save
    end
    redirect_to(:controller => "orders", :action => "show")
  end
  
  def remove_item
    OrderItem.delete(params[:order_item_id])
    redirect_to(:controller => "orders", :action => "show")
  end
  
  def confirm
    @order = Order.find(params[:id])
    @order.confirmed = true
    @order.save
    Order.create(buyer_id: current_buyer().id, confirmed: false)
    redirect_to(:controller => "shop", :action => "index")
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @q = Product.search(params[:q])
    @products = @q.result(:distinct => true)
    @is_search = params[:q] != nil 
    
    respond_to do |format|
      format.json { render :json => @products }
    end
     
  end
  
  def show
    @product = Product.find_by_id(params[:id])
  end
  
  def search
    @q = Product.search
  end
  
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
    @categories = Category.all();
  end
end

app/controllers/spa_controller.rb
class SpaController < ApplicationController
  def index
    @products = Product.all()
    @categories = Category.all()
  end
  
  def confirmOrder
    @order = Order.create
    @items = params[:items]
    for item in @items
      oItem = OrderItem.create
      oItem.quantity = item[1][:quantity]
      oItem.product_id = item[1][:product_id]
      oItem.order_id = @order.id
      oItem.save
    end
    
    respond_to do |format|
      format.json { render :json => @order }
    end
  end
    
  def getProducts
    @products = Product.all()
    respond_to do |format|
      format.json { render :json => @products }
    end 
  end
    
  def getCategories
    @categories = Category.all()
    respond_to do |format|
      format.json { render :json => @categories }
    end
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/admin/categories/index.html.erb
<% @categories.each do |c|%>
<p><%= link_to c.name, :controller => "admin/categories", :action => "show", :id => c.id %></p>
<% end %>
<%= link_to "New", :controller => "admin/categories", :action => "new" %>

app/views/admin/categories/new.html.erb
<%= form_for @category, :url => { :action => "create" }, do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/admin/categories/show.html.erb
<%= form_for @category, :url => { :action => "update" }, do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Update" %>
<% end %>

<%= link_to "Delete", admin_category_path(@category), :action => "destroy", :method => :delete %>

app/views/admin/orders/index.html.erb
<% @orders.each do |o| %>
<p><%= link_to o.id, admin_order_path(o.id) %></p>
<%end%>

app/views/admin/orders/show.html.erb
<p>
	Order no.: <%= @order.id %>
</p>
<p>
	Buyer: <%=@order.buyer.id%>
</p>
<p>
	<table border="1">
		<tr>
			<td>ID</td>
			<td>Product name</td>
			<td>Quantity</td>
			<td>Unit price</td>
			<td>Total price</td>
		</tr>
		<% @order_items.each do |item|%>
		<tr>
			<td><%=item.product.id%></td>
			<td><%=item.product.name%></td>
			<td><%=item.quantity%></td>
			<td><%=item.price%></td>
			<td><%=item.price * item.quantity%></td>
		</tr>
		<% end %>
	</table>
</p>

app/views/admin/products/index.html.erb
<% @products.each do |p|%>
<p><%= link_to p.name, :controller => "admin/products", :action => "show", :id => p.id %></p>
<% end %>
<%= link_to "New", :controller => "admin/products", :action => "new" %>

app/views/admin/products/new.html.erb
<%= form_for @product, :url => { :action => "create" }, do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :price %>
  <%= f.select(:category, @categories)%>
  <%= f.submit "Create" %>
<% end %>

app/views/admin/products/show.html.erb
<%= form_for @product, :url => { :action => "update" }, do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :price %>
  <%= f.select(:category, @categories)%>
  <%= f.submit "Update" %>
<% end %>

<%= link_to "Delete", admin_product_path(@product), :action => "destroy", :method => :delete %>

app/views/categories/show.html.erb
<h1>Category: <%=@category.name%></h1>
<% @products.each do |prod| %>
	<p>
		<span class="product_link"><%= link_to prod.name, :controller => "products", :action => "show", :id => prod.id %></span>
	</p>
<% end %>

app/views/orders/cart.html.erb
<p>
	Order no.: <%= @cart.id %>
</p>
<p>
	Buyer: <%=@current_buyer.id%>
</p>
<p>
	<table border="1">
		<tr>
			<td>ID</td>
			<td>Product name</td>
			<td>Quantity</td>
			<td>Unit price</td>
			<td>Total price</td>
			<td>Remove</td>
		</tr>
		<% current_cart.each do |item|%>
		<tr>
			<td><%=item.product.id%></td>
			<td><%=item.product.name%></td>
			<td><%=item.quantity%></td>
			<td><%=item.price%></td>
			<td><%=item.price * item.quantity%></td>
			<td><%= link_to "X", :controller => "orders", :action => "remove_item", :order_item_id => item.id %></td>
		</tr>
		<% end %>
	</table>
</p>
<%= link_to "Checkout", :controller => "orders", :action => "confirm", :id => @cart.id %>

app/views/orders/show.html.erb
<p>
	Order no.: <%= @cart.id %>
</p>
<p>
	Buyer: <%=@current_buyer.id%>
</p>
<p>
	<table border="1">
		<tr>
			<td>ID</td>
			<td>Product name</td>
			<td>Quantity</td>
			<td>Unit price</td>
			<td>Total price</td>
			<td>Remove</td>
		</tr>
		<% current_cart.each do |item|%>
		<tr>
			<td><%=item.product.id%></td>
			<td><%=item.product.name%></td>
			<td><%=item.quantity%></td>
			<td><%=item.price%></td>
			<td><%=item.price * item.quantity%></td>
			<td><%= link_to "X", :controller => "orders", :action => "remove_item", :order_item_id => item.id %></td>
		</tr>
		<% end %>
	</table>
</p>
<%= link_to "Checkout", :controller => "orders", :action => "confirm", :id => @cart.id %>

app/views/products/index.html.erb
<%if @products.size == 0 %>

<p>No products matches submitted criteria</p>
<p>Try to:  
	<span><%= link_to "change search criteria", :controller => "products", :action => "search" %></span>
	or
	<span><%= link_to "show all products", :controller => "products", :action => "index" %></span>
</p>

<%elsif @is_search %>

<p>Found <%=@products.size%> products.</p>

<%end%>

<% @products.each do |prod| %>
	<p>
		<span class="product_link"><%= link_to prod.name, :controller => "products", :action => "show", :id => prod.id %></span>
	</p>
<% end %>

app/views/products/search.html.erb
<%= search_form_for @q do |f| %>
  <%= f.label :name_cont %>
  <%= f.text_field :name_cont %>
  <%= f.label :description_cont %>
  <%= f.text_field :description_cont %>
  <%= f.label :price_gteq %>
  <%= f.text_field :price_gteq %>
  <%= f.label :price_lt %>
  <%= f.text_field :price_lt %>
  <%= f.submit %>
<% end %>

app/views/products/show.html.erb
<p>
	Category: 
	<span class="product_link">
		<%= link_to @product.category.name, :controller => "categories", :action => "show", :id => @product.category_id %>
	</span>
<p>
	<span class="product_name">Product: <%= @product.name %></span>
	<span class="product_price">Price: <%= "%.2f" % @product.price %> zł.</span>
	<p>
		Description: 
		<%= @product.description %>
	</p>
</p>
<p>
	<%= link_to "Add to cart", :controller => "orders", :action => "add_product", :product_id => @product.id %>
</p>